# Generated by Django 6.0 on 2025-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('espece', models.CharField(choices=[('CHIEN', 'Chien'), ('CHAT', 'Chat')], max_length=10, verbose_name='Espèce')),
                ('age_annees', models.IntegerField(verbose_name='Âge (années)')),
                ('age_mois', models.IntegerField(default=0, verbose_name='Âge (mois supplémentaires)')),
                ('categorie_age', models.CharField(choices=[('junior', 'Junior (moins de 2 ans)'), ('adulte', 'Adulte (2 à 7 ans)'), ('senior', 'Senior (plus de 7 ans)')], max_length=10, verbose_name="Catégorie d'âge")),
                ('sexe', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femelle')], max_length=1, verbose_name='Sexe')),
                ('race', models.CharField(blank=True, max_length=100, verbose_name='Race')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='animaux/', verbose_name='Photo')),
                ('date_arrivee', models.DateField(auto_now_add=True, verbose_name="Date d'arrivée")),
                ('disponible', models.BooleanField(default=True, verbose_name="Disponible à l'adoption")),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
                'ordering': ['-date_arrivee'],
            },
        ),
    ]
