# Generated by Django 6.0 on 2026-01-13 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(help_text='Format: 06 12 34 56 78 ou 0612345678', max_length=20, verbose_name='Téléphone')),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse complète (optionnel)')),
                ('type_logement', models.CharField(choices=[('MAISON_JARDIN', 'Maison avec jardin'), ('MAISON_SANS_JARDIN', 'Maison sans jardin'), ('APPARTEMENT_BALCON', 'Appartement avec balcon'), ('APPARTEMENT_SANS_BALCON', 'Appartement sans balcon')], max_length=30, verbose_name='Type de logement')),
                ('statut_logement', models.CharField(choices=[('PROPRIETAIRE', 'Propriétaire'), ('LOCATAIRE', 'Locataire (autorisation du propriétaire)')], max_length=20, verbose_name='Statut du logement')),
                ('a_autres_animaux', models.BooleanField(default=False, verbose_name="Possède d'autres animaux")),
                ('details_autres_animaux', models.CharField(blank=True, help_text='Ex: 1 chat, 1 lapin', max_length=200, verbose_name='Si oui, lesquels ?')),
                ('motivation', models.TextField(help_text='Minimum 50 caractères', verbose_name='Pourquoi voulez-vous adopter cet animal ?')),
                ('disponibilite', models.CharField(choices=[('CETTE_SEMAINE', 'Cette semaine'), ('1_SEMAINE', 'Dans 1 semaine'), ('2_SEMAINES', 'Dans 2 semaines'), ('1_MOIS', 'Dans 1 mois'), ('FLEXIBLE', 'Flexible')], default='FLEXIBLE', max_length=20, verbose_name='Quand pouvez-vous venir ?')),
                ('precisions_disponibilite', models.CharField(blank=True, help_text="Ex: Plutôt en fin d'après-midi", max_length=200, verbose_name='Précisions sur vos disponibilités (optionnel)')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('traitee', models.BooleanField(default=False, verbose_name='Demande traitée')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_adoption', to='animaux.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': "Demande d'adoption",
                'verbose_name_plural': "Demandes d'adoption",
                'ordering': ['-date_demande'],
            },
        ),
    ]
