# Generated by Django 6.0 on 2026-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0002_demandeadoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeadoption',
            name='adresse',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='demandeadoption',
            name='details_autres_animaux',
            field=models.CharField(blank=True, max_length=200, verbose_name='Si oui, lesquels ?'),
        ),
        migrations.AlterField(
            model_name='demandeadoption',
            name='motivation',
            field=models.TextField(verbose_name='Pourquoi voulez-vous adopter cet animal ?'),
        ),
        migrations.AlterField(
            model_name='demandeadoption',
            name='precisions_disponibilite',
            field=models.CharField(blank=True, max_length=200, verbose_name='Précisions sur vos disponibilités (optionnel)'),
        ),
        migrations.AlterField(
            model_name='demandeadoption',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterUniqueTogether(
            name='demandeadoption',
            unique_together={('email', 'animal')},
        ),
    ]
