# Generated by Django 6.0 on 2026-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0003_alter_demandeadoption_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeadoption',
            name='disponibilite',
            field=models.CharField(choices=[('CETTE_SEMAINE', 'Cette semaine'), ('1_SEMAINE', 'Dans 1 semaine'), ('2_SEMAINES', 'Dans 2 semaines'), ('1_MOIS', 'Dans 1 mois'), ('FLEXIBLE', 'Flexible')], max_length=20, verbose_name='Quand pouvez-vous venir ?'),
        ),
    ]
