# Generated by Django 6.0 on 2026-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0004_alter_demandeadoption_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadoption',
            name='notes_admin',
            field=models.TextField(blank=True, verbose_name='Notes administrateur (privé)'),
        ),
        migrations.AddField(
            model_name='demandeadoption',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', '⏳ En attente'), ('ACCEPTEE', '✅ Acceptée'), ('REFUSEE', '❌ Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de la demande'),
        ),
        migrations.AlterField(
            model_name='demandeadoption',
            name='adresse',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adresse'),
        ),
    ]
