# Generated by Django 6.0 on 2026-01-29 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0005_demandeadoption_notes_admin_demandeadoption_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadoption',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_adoption', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
