# Generated by Django 6.0 on 2026-01-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
